<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions">
      <Version>8.10.0</Version>
    </PackageReference>
    <PackageReference Include="Moq">
      <Version>4.20.72</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk">
      <Version>17.14.0</Version>
    </PackageReference>
    <PackageReference Include="NUnit">
      <Version>4.3.2</Version>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter">
      <Version>5.0.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirSerbiaVirtua.Contracts\AirSerbiaVirtua.Contracts.csproj" />
    <ProjectReference Include="..\AirSerbiaVirtua.Acars.Core\AirSerbiaVirtua.Acars.Core.csproj" />
    <ProjectReference Include="..\AirSerbiaVirtua.Acars.Desktop\AirSerbiaVirtua.Acars.Desktop.csproj" />
  </ItemGroup>

</Project>
