// <auto-generated />
using System;
using AirSerbiaVirtua.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirSerbiaVirtua.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602194343_AddPilotPasswordHash")]
    partial class AddPilotPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HubId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Selcal")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.ToTable("Aircraft");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HubId = "LYBE",
                            Registration = "YU-API",
                            Selcal = "AB-CD",
                            Status = "Active",
                            Type = "A319"
                        },
                        new
                        {
                            Id = 2,
                            HubId = "LYBE",
                            Registration = "YU-APB",
                            Selcal = "AE-FG",
                            Status = "Active",
                            Type = "A320"
                        },
                        new
                        {
                            Id = 3,
                            HubId = "LYBE",
                            Registration = "YU-APN",
                            Selcal = "AH-JK",
                            Status = "Active",
                            Type = "A320neo"
                        },
                        new
                        {
                            Id = 4,
                            HubId = "LYBE",
                            Registration = "YU-APM",
                            Selcal = "AL-MP",
                            Status = "Active",
                            Type = "A321neo"
                        },
                        new
                        {
                            Id = 5,
                            HubId = "LYBE",
                            Registration = "YU-ALP",
                            Selcal = "AQ-RS",
                            Status = "Active",
                            Type = "ATR72"
                        },
                        new
                        {
                            Id = 6,
                            HubId = "LYBE",
                            Registration = "YU-AED",
                            Selcal = "BC-DF",
                            Status = "Active",
                            Type = "E195"
                        },
                        new
                        {
                            Id = 7,
                            HubId = "LYBE",
                            Registration = "YU-ARA",
                            Selcal = "BG-HJ",
                            Status = "Active",
                            Type = "A330"
                        });
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Airport", b =>
                {
                    b.Property<string>("Icao")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Elevation")
                        .HasColumnType("integer");

                    b.Property<string>("Iata")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Icao");

                    b.HasIndex("Iata");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Icao = "LYBE",
                            Country = "Serbia",
                            Elevation = 335,
                            Iata = "BEG",
                            Lat = 44.818399999999997,
                            Lon = 20.309100000000001,
                            Name = "Belgrade Nikola Tesla Airport",
                            Revision = 2026
                        });
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PilotId")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("PilotId", "RouteId", "Date")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HubId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("PasswordUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric(9,1)");

                    b.HasKey("Id");

                    b.HasIndex("Callsign")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HubId");

                    b.HasIndex("RankId");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Pirep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirMin")
                        .HasColumnType("integer");

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ArrActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BlockMin")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DepActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FuelUsedKg")
                        .HasColumnType("integer");

                    b.Property<int>("LandingRateFpm")
                        .HasColumnType("integer");

                    b.Property<int>("PilotId")
                        .HasColumnType("integer");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("PilotId");

                    b.HasIndex("RouteId");

                    b.HasIndex("Status");

                    b.ToTable("Pireps");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.PositionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AltFt")
                        .HasColumnType("integer");

                    b.Property<int>("GsKts")
                        .HasColumnType("integer");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PirepId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PirepId", "Timestamp");

                    b.ToTable("PositionLogs");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedAircraftTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("MinHours")
                        .HasColumnType("numeric(8,1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedAircraftTypes = "[\"ATR72\",\"E195\"]",
                            MinHours = 0m,
                            Name = "Cadet"
                        },
                        new
                        {
                            Id = 2,
                            AllowedAircraftTypes = "[\"ATR72\",\"E195\",\"A319\",\"A320\",\"A320neo\"]",
                            MinHours = 50m,
                            Name = "First Officer"
                        },
                        new
                        {
                            Id = 3,
                            AllowedAircraftTypes = "[\"ATR72\",\"E195\",\"A319\",\"A320\",\"A320neo\",\"A321neo\"]",
                            MinHours = 200m,
                            Name = "Senior First Officer"
                        },
                        new
                        {
                            Id = 4,
                            AllowedAircraftTypes = "[\"ATR72\",\"E195\",\"A319\",\"A320\",\"A320neo\",\"A321neo\",\"A330\"]",
                            MinHours = 500m,
                            Name = "Captain"
                        },
                        new
                        {
                            Id = 5,
                            AllowedAircraftTypes = "[\"ATR72\",\"E195\",\"A319\",\"A320\",\"A320neo\",\"A321neo\",\"A330\"]",
                            MinHours = 1500m,
                            Name = "Senior Captain"
                        });
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ArrIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DepIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PlannedTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArrIcao");

                    b.HasIndex("DepIcao");

                    b.HasIndex("FlightNumber")
                        .IsUnique();

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Aircraft", b =>
                {
                    b.HasOne("AirSerbiaVirtua.Api.Models.Airport", "Hub")
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Booking", b =>
                {
                    b.HasOne("AirSerbiaVirtua.Api.Models.Pilot", "Pilot")
                        .WithMany("Bookings")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirSerbiaVirtua.Api.Models.Route", "Route")
                        .WithMany("Bookings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pilot");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Pilot", b =>
                {
                    b.HasOne("AirSerbiaVirtua.Api.Models.Airport", "Hub")
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirSerbiaVirtua.Api.Models.Rank", "Rank")
                        .WithMany("Pilots")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hub");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Pirep", b =>
                {
                    b.HasOne("AirSerbiaVirtua.Api.Models.Aircraft", "Aircraft")
                        .WithMany("Pireps")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirSerbiaVirtua.Api.Models.Pilot", "Pilot")
                        .WithMany("Pireps")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirSerbiaVirtua.Api.Models.Route", "Route")
                        .WithMany("Pireps")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Pilot");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.PositionLog", b =>
                {
                    b.HasOne("AirSerbiaVirtua.Api.Models.Pirep", "Pirep")
                        .WithMany("PositionLogs")
                        .HasForeignKey("PirepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pirep");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Route", b =>
                {
                    b.HasOne("AirSerbiaVirtua.Api.Models.Airport", "Arrival")
                        .WithMany()
                        .HasForeignKey("ArrIcao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirSerbiaVirtua.Api.Models.Airport", "Departure")
                        .WithMany()
                        .HasForeignKey("DepIcao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arrival");

                    b.Navigation("Departure");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Aircraft", b =>
                {
                    b.Navigation("Pireps");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Pilot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Pireps");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Pirep", b =>
                {
                    b.Navigation("PositionLogs");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Rank", b =>
                {
                    b.Navigation("Pilots");
                });

            modelBuilder.Entity("AirSerbiaVirtua.Api.Models.Route", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Pireps");
                });
#pragma warning restore 612, 618
        }
    }
}
